### ISSUE TITLE
[Question] NFS server options.

### ISSUE THREAD

**Issue by blmhemu** [bjw-s/k8s-gitops#114]
Can you explain a bit on the server side options of NFS ?
Are you using root_squash ?
If yes then how are you managing all the user permissions ? A lot of containers/pods chown to different users:groups and it becomes a bit hectic to keep track of all of them.

**Comment by bjw-s** [comment]
Hi!
I wish I could give you a really elaborate answer, but I'm not doing anything fancy on the server side. 
Basically I have the users on my NFS server set up with the correct UID/GID that are required by the containers that I am running. For some containers I override the UID/GID by specifying the podSecurityContext.
