### ISSUE TITLE
Implement pull-through image cache

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/k8s-gitops#13]
Because of the impending rate limits on Docker Hub I need to set up a pull-through cache.

Most likely solution: run the Nexus as a docker container on my NAS and add that as a mirror repository to the k3s config

**Comment by bjw-s** [comment]
Implemented by running Nexus registry on NAS

**Comment by onedr0p** [comment]
I was just going to post this.
https://github.com/onedr0p/k3s-gitops/issues/62

Glad you got it working!
