### ISSUE TITLE
Investigate Auth0 / Keycloak implementation

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/k8s-gitops#329]
**Context:**
Currently I mostly rely on service built-in authentication mechanisms. It would be better / easier to set up a separate authentication mechanism so that I can centralise my user accounts, and possibly even implement SSO.

**Related issues:**
- https://github.com/billimek/k8s-gitops/issues/36

**Comment by NegativeFeedback** [comment]
I just went through this and found vouch-proxy and keycloak slightly easier to setup

**Comment by bjw-s** [comment]
I now have oauth2-proxy and Keycloak up and running after a brief dalliance with Auth0 so this one can finally be closed :)
