### ISSUE TITLE
Implement a solution for Longhorn backups > cloud backups

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/k8s-gitops#6]
Currently all backups are on the local network. For additional security I want to add a cloud backup of this data in the mix.

Should look at how @onedr0p does this with rclone to Backblaze B2
https://github.com/onedr0p/k3s-gitops/tree/master/deployments/default/rclone

**Comment by ricky-sb** [comment]
Seems like it's a cron job with rclone copying files directly from a particular path.  

https://github.com/onedr0p/home-cluster/blob/main/cluster/velero/jobs/velero-minio-b2-sync.yaml  

So rclone is sweeping the files on a particular schedule. I wonder if there's a more elegant way to do this. [According to this article](https://www.backblaze.com/blog/how-to-use-minio-with-b2-cloud-storage/), "Minio acts as a gateway to B2 and will automatically and transparently put or get data into a Backblaze B2 account", so I I don't understand where rclone comes in (in his particular implementation).  

I'm mostly interested in being able to `rclone mount` a volume, and have Longhorn save files to it directly. Or have Longhorn integrate with rclone directly somehow.

**Comment by ricky-sb** [comment]
Maybe something like this: https://forum.rclone.org/t/rclone-serve-s3-remote/8721/  

Unfortunately, there's no progress on that, but that seems interesting. rclone behaving as an S3-compliant server and proxying requests to whatever cloud backend you want.

**Comment by bjw-s** [comment]
It took me some time, but I've finally gotten to creating the Minio -> B2 rclone job.
https://github.com/bjw-s/k8s-gitops/tree/main/cluster/namespaces/system-velero/velero-minio-b2-sync
