### ISSUE TITLE
Modify the CI Runner to a RunnerDeployment to allow parallel runners?

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/k8s-gitops#9]
Currently I have a single Runner ([actions-runner-controller](https://github.com/summerwind/actions-runner-controller)) for this repo. Maybe I should modify this to a RunnerDeployment so I can have two parallel runners.

**Comment by onedr0p** [comment]
I was thinking about doing this as well! I don't think it would be a difficult change. I only haven't done it yet because I don't have any jobs that run concurrently on this runner in my CI.

**Comment by bjw-s** [comment]
Done :) See https://github.com/bjw-s/k8s-gitops/blob/master/deployments/actions-runner-system/actions-runner-system/runners/runnerdeployment-gitops.yaml

Added in autoscaling for now, but might revert to fixed # of replicas
https://github.com/summerwind/actions-runner-controller/blob/master/README.md#autoscaling
